"[client]\nshowSidebarNavigation = false\n\n[theme]\nprimaryColor = \"#FF4B4B\"\nbackgroundColor = \"#FFFFFF\"\nsecondaryBackgroundColor = \"#F0F2F6\"\ntextColor = \"#262730\"\nfont = \"sans serif\"" 
